#!/usr/bin/env sh                            

# general space settings
yabai -m config layout                       bsp
yabai -m config top_padding                  15
yabai -m config bottom_padding               15
yabai -m config left_padding                 15
yabai -m config right_padding                15
yabai -m config window_gap                   15

# Spaces
yabai -m space 1 --label one
yabai -m space 2 --label two
yabai -m space 3 --label three
yabai -m space 4 --label four
yabai -m space 5 --label five

# float preferences
yabai -m rule --add app="^System Preferences$" manage=off
yabai -m rule --add app="^Finder$" manage=off
yabai -m rule --add app="^Disk Utility$" manage=off
yabai -m rule --add app="^scrcpy$" manage=off
yabai -m rule --add app="^System Information$" manage=off
yabai -m rule --add app="^Activity Monitor$" manage=off
yabai -m rule --add app="^Spotify$" manage=off
yabai -m rule --add app="^Messages$" manage=off
#yabai -m rule --add app="^zoom.us$" manage=off
yabai -m rule --add app="^Preview$" manage=off
yabai -m rule --add app="^Yukino$" manage=off
yabai -m rule --add app="^Photos$" manage=off
yabai -m rule --add app="^Books$" manage=off
yabai -m rule --add app="^Calculator$" manage=off
yabai -m rule --add app="^Photo\ Booth$" manage=off
yabai -m rule --add app="^OpenEmu$" manage=off
yabai -m rule --add app="^sixtyforce$" manage=off
#yabai -m rule --add app="^Discord$" manage=off
yabai -m rule --add app="^Dash$" manage=off
yabai -m rule --add app="^Music$" manage=off
yabai -m rule --add app="^BlueJ$" manage=off
yabai -m rule --add app="^Emacs$" manage=on

# kill any existing limelight process if one exists, before we launch a new one
killall limelight &> /dev/null
limelight &> /dev/null &

#global settings
yabai -m config status_bar                   on
yabai -m config mouse_follows_focus          off
yabai -m config focus_follows_mouse          off
yabai -m config window_placement             second_child
yabai -m config window_topmost               off
yabai -m config window_shadow                off
yabai -m config window_opacity               off
yabai -m config insert_feedback_color        0xffd75f5f
yabai -m config split_ratio                  0.50
yabai -m config auto_balance                 off
yabai -m config mouse_modifier               ctrl
yabai -m config mouse_action1                move
yabai -m config mouse_action2                resize
yabai -m config mouse_drop_action            swap


yabai -m config external_bar all:28:0


echo "yabai configuration loaded.."
